Get the current LobbySettings
---
tags:
  - Lobby
parameters:
  - in: path
    name: lobbyID
    required: True
    description: The LobbyID to get the Settings from
    schema:
      type: Integer
responses:
  200:
    description: LobbySettings found
  204:
    description: No Lobbysettings available